name: my-docker-project

services:
    app:
        image: postgres:latest
        container_name: my_postgres_container
        ports:
            - "5431:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        restart: unless-stopped
        volumes:
            - ./postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
        
